apiVersion: v1
kind: Secret
metadata:
  name: cookie
  namespace: {{ include "ack-prow.prowNamespace" . }}
  labels:
    {{- include "ack-prow.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.github.cookieSecret | b64enc | quote }}