apiVersion: v1
kind: Secret
metadata:
  name: github-app
  namespace: {{ include "ack-prow.prowNamespace" . }}
  labels:
    {{- include "ack-prow.labels" . | nindent 4 }}
type: Opaque
data:
  app-id: {{ .Values.github.app.id | b64enc | quote }}
  private-key: {{ .Values.github.app.privateKey | b64enc | quote }}