apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
  namespace: {{ include "ack-prow.prowNamespace" . }}
  labels:
    {{- include "ack-prow.labels" . | nindent 4 }}
type: Opaque
data:
  hmac: {{ .Values.github.hmacToken | b64enc | quote }}