apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ include "ack-prow.prowNamespace" . }}
  labels:
    {{- include "ack-prow.labels" . | nindent 4 }}
stringData:
  service-account.json: |
    {
      "region": "{{ .Values.aws.region }}",
      "access_key": "{{ .Values.aws.s3.credentials.accessKey }}",
      "endpoint": "{{ .Values.aws.s3.credentials.endpoint }}",
      "insecure": {{ .Values.aws.s3.credentials.insecure }},
      "s3_force_path_style": {{ .Values.aws.s3.forcePathStyle }},
      "secret_key": "{{ .Values.aws.s3.credentials.secretKey }}"
    }