apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prow
  labels:
    app: prow
    {{- include "ack-prow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch