{{- if .Values.workflowAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runner
  namespace: {{ .Values.prowConfig.prowJobNamespace }}
  labels:
    app: workflow-runner
    {{- include "ack-prow.labels" . | nindent 4 }}
  {{- if .Values.aws.s3.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.s3.roleArn }}
  {{- end }}
{{- end }}