{{- if .Values.workflowAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-agent
  namespace: {{ include "ack-prow.prowNamespace" . }}
  labels:
    app: workflow-agent
    {{- include "ack-prow.labels" . | nindent 4 }}
{{- end }}